<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Connect_wheel_slide_popup_</name>
   <tag></tag>
   <elementGuidId>e8ae8469-afa9-412f-8f3b-f3ca1553effd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='CHOOSE MAKE'])[1]/preceding::div[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div[3]/div[4]/div/div[1]/div/div/div[1]/div/iknow-mjpopup/ggc-mj-popup/div[1][count(. | //div[@data-ng-class = concat('mjShow ? ' , &quot;'&quot; , 'wheel_slide_popup_mask_active' , &quot;'&quot; , ':' , &quot;'&quot; , 'wheel_slide_popup_mask') and @ng-click = 'mjHide()' and @role = 'button' and @tabindex = '0' and @class = 'wheel_slide_popup_mask_active']) = count(//div[@data-ng-class = concat('mjShow ? ' , &quot;'&quot; , 'wheel_slide_popup_mask_active' , &quot;'&quot; , ':' , &quot;'&quot; , 'wheel_slide_popup_mask') and @ng-click = 'mjHide()' and @role = 'button' and @tabindex = '0' and @class = 'wheel_slide_popup_mask_active'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>mjShow ? 'wheel_slide_popup_mask_active':'wheel_slide_popup_mask'</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>mjHide()</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wheel_slide_popup_mask_active</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div[3]/div[4]/div/div[1]/div/div/div[1]/div/iknow-mjpopup/ggc-mj-popup/div[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CHOOSE MAKE'])[1]/preceding::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//iknow-mjpopup/ggc-mj-popup/div</value>
   </webElementXpaths>
</WebElementEntity>
