<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_2017 Ford Edge SE  Lorenzo</name>
   <tag></tag>
   <elementGuidId>66b8742a-10c4-4c59-b725-f21ef96b5bd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='config_mob']/div[4]/div/div[3]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@class = 'result_summsry_top_dv' and @ng-click = 'getCarDetailsClick(car)' and @role = 'button' and @tabindex = '0' and (text() = '  2017 Ford Edge SE  Lorenzo Ford  8953 mi Away     $21,886 $30,040   You saved $8,154       Loan $337/Mo   Lease $318/Mo    ' or . = '  2017 Ford Edge SE  Lorenzo Ford  8953 mi Away     $21,886 $30,040   You saved $8,154       Loan $337/Mo   Lease $318/Mo    ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>result_summsry_top_dv</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>getCarDetailsClick(car)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  2017 Ford Edge SE  Lorenzo Ford  8953 mi Away     $21,886 $30,040   You saved $8,154       Loan $337/Mo   Lease $318/Mo    </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;config_mob&quot;)/div[@class=&quot;dv_equal_height&quot;]/div[@class=&quot;result_pop_dv&quot;]/div[@class=&quot;result_summsry_top_dv&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='config_mob']/div[4]/div/div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='STOCK# HBB77957'])[1]/following::div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIN# 2FMPK3G99HBB77957'])[1]/following::div[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div/div/div[3]/div[4]/div/div[3]</value>
   </webElementXpaths>
</WebElementEntity>
