<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Assistance_md-bar</name>
   <tag></tag>
   <elementGuidId>4db3a867-92f0-4114-89fc-2b494285999a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//md-switch[@id='large']/div/div)[3]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;navigation-box&quot;)/div[@class=&quot;bot_wrap botwrap_sm&quot;]/div[@class=&quot;botwrap_main&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;sggst_bxlst chatbot-navigate-icon&quot;]/div[1]/md-switch[@id=&quot;large&quot;]/div[@class=&quot;md-container&quot;]/div[@class=&quot;md-bar&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md-bar</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navigation-box&quot;)/div[@class=&quot;bot_wrap botwrap_sm&quot;]/div[@class=&quot;botwrap_main&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;sggst_bxlst chatbot-navigate-icon&quot;]/div[1]/md-switch[@id=&quot;large&quot;]/div[@class=&quot;md-container&quot;]/div[@class=&quot;md-bar&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>(//md-switch[@id='large']/div/div)[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assistance'])[2]/following::div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GOT IT'])[1]/following::div[9]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gogo'])[2]/preceding::div[8]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[2]/div/div/div/div/div/md-switch/div/div</value>
   </webElementXpaths>
</WebElementEntity>
