<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>close_employee_drawer</name>
   <tag></tag>
   <elementGuidId>8e5d9480-0da8-4e4b-b1ea-aecbb205e1cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;close_emp_drawer&quot;][count(. | //*[@id = 'close_emp_drawer']) = count(//*[@id = 'close_emp_drawer'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>close_emp_drawer</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;close_emp_drawer&quot;]</value>
   </webElementProperties>
</WebElementEntity>
