<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_BUILD YOUR DREAM CAR  Home</name>
   <tag></tag>
   <elementGuidId>3cefe690-b0f7-47fc-a775-80c692a9fec7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div[4]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ui-view</name>
      <type>Main</type>
      <value>content</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>                                 BUILD YOUR DREAM CAR  Home  / Build your dream car  Use our Car Building capability to research &amp; narrow down on your dream cars. You can find the cars you are looking for by either searching by Make, Model, Type, Budget etc. You can also search with a stock number or VIN. While you are researching your new car, we will continue to provide you best recommendations and alternatives so that you can choose the best options out there.       I know what I want   I Know what I want     Make Model Year Trim                     I have no clue   I have no clue    Type  MPG  Features                        I have a budget   I have a budget    Type Features Budget                    Search          New Cars      Pre Owned Cars     Edit   Make       Acura       Edit   Model     ILX       Edit   Year     2017       Edit   Trim     Base        SELECT &amp; CONTINUE Reset all                DECIDE AND BUY All the critical information you need to decide and buy your next dream car       REAL SAVINGS Access all discounts, offers and incentives        Hassle Free Experience Know you're receiving the best price without a hassle         SELECT &amp; CONTINUE Reset all                                                            Nearby Dealers      Yonkers Kia New  791 mi away      Yonkers Kia  791 mi away      World Volkswagen of Neptune  791 mi away      World Jeep Chrysler Dodge And Ram  791 mi away          2015-’18 GoGoCar LLCAll rights reserved                        </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;consumer&quot;]/div[@class=&quot;dv_container config_bg&quot;]/div[@class=&quot;notranslate&quot;]/div[@class=&quot;dv_container&quot;]/div[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[3]/div[4]/div</value>
   </webElementXpaths>
</WebElementEntity>
